drop table messages;
drop table users_to_chat;
drop table groups;
drop table conversation_info;
drop table conversations;
drop table chats;
drop table uncatch_alert;
drop table users;
drop table photos;
