delete from messages;
delete from users_to_chat;
delete from groups;
delete from conversation_info;
delete from conversations;
delete from chats;
delete from uncatch_alert;
delete from users;
delete from photos;
