package constant;

public enum MessageType {
	MESSAGE, NOTIFICATION, UPDATE_CHAT_USER, ADD_USER_CHAT, DELETE_USER_CHAT,
	PUSHED_USER_OUT,  REQUESTED_CHAT, NEW_CHAT, UPDATE_WHO_IS_WRITING,
	UPDATE_GROUP_NAME, UPDATE_GROUP_PHOTO, UPDATE_USER_PHOTO
}
